### PR TITLE
Add basic theming reminding on riot light theme.

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
I picked the light/base theme and applied it partially on your site:
riot-static-base-theme

### CODE REVIEW

**Comment by t3chguy** [comment]
looks gentle and non-intrusive, will have a play :)

**Comment by t3chguy** [comment]
I like it in general but doesn't look great on white background avatars:
image

**Comment by t3chguy** [comment]
I think setting the appropriate corner rounding on these Logo Missing avatars may make it look better

**Comment by Ryuno-Ki** [comment]
The correct solution would be transparent background for white …
I'm investigating, what's possible.

**Comment by Ryuno-Ki** [comment]
I created a version with transparent background. You would need to compile it before deploying, because I have no Go on my machine. If you don't want to use it, please at least keep it, so I could try applying `mask: url(./assets/img/logo_missing_transparent.png) alpha`

**Comment by t3chguy** [comment]
@Ryuno-Ki its not simply for those logos with white backgrounds, other avatars have the issue too. I am ***almost*** not using that image anymore anyways, see sneak preview:

image

(it generates character "T" etc avatars)

**Comment by t3chguy** [comment]
I'll look into how your front page css looks with the latest changes shortly

**Comment by Ryuno-Ki** [comment]
Is affected by #15.

**Pull request merged**
